### ISSUE TITLE
Stream to VK.com

### ISSUE THREAD

**Issue by alexeysvrv** [tcarrio/ffmpeg-streamcast#1]
Hi. Help me please create stream sh script. I have monitor 1600x1200 res. Output 1280x720 must been. I Russian. Sorry for language. Record my desktop with acc audio codec. https://vk.com/page-135678176_54378816 - parametres of stream

**Comment by tcarrio** [comment]
I can look into this during the weekend. Seems the script I have should be roughly compatible with that. A big thing is whether VK has a key-based system that will accept the stream in a similar fashion. Most likely. 

I will send updates here

**Comment by alexeysvrv** [comment]
Thank you @tcarrio

**Comment by tcarrio** [comment]
@alexeysvrv  Please try using the latest commit (250fe6e...) which includes the `streamcast2vk.sh` script and reference the `HOW-TO/VK.com` docs.

**Comment by alexeysvrv** [comment]
Thank you very much! Everything is working! You helped me a lot!
Also, if it's not hard for you, can you make a video capture script from a webcam? And the streaming from the web camera to the stream from the desktop (in the corner with the camera, I think you know). Camera 640x480
